import type { Metadata } from 'next'
import { Locale } from '@/i18n.config'
import ListListen from '@/app/components/Listen/ListListen'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,params:{lang}
}: {
  children: React.ReactNode,
  params:{lang:Locale}
}) {
  return (
        <>
            <ListListen lang={lang}/>
            {children}
        </>
  )
}
