import type { Metadata } from 'next'
import { Locale } from '@/i18n.config'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export function generateStaticParams({params:{category}}:{params:{category:string}}) {
  if(category==="latest")return [{sortfor:'date'}];
  else if(category==="most popular")[{sortfor:"views"}]
  return [{sortfor:'date'},{sortfor:'views'},{sortfor:'name'}]
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        children
  )
}
